#!/usr/bin/env ruby
require 'optparse'

options = {}

class Parser
  def self.parse(args)
    options = {}
    opt_parser = OptionParser.new do |opts|
      opts.banner = 'Usage: demo.rb [options] ARG...'
      
      opts.separator ''
      opts.separator 'Options:'

      opts.on('-nNAME', '--name=NAME', 'Name to say hello to') do |n|
        options[:name] = n
      end
      
      opts.on('-v', '--[no-]verbose', 'Run verbosely') do |v|
        options[:verbose] = v
      end
      
      opts.on('-h', '--help', 'Prints this help') do
        puts opts
        exit
      end
    end

    opt_parser.parse!(args)
    return options
  end
end

begin
  options = Parser.parse ARGV
rescue Exception => e
  puts "Exception encountered: #{e}"
  exit 1
end
  
Parser.parse %w[--help] if ARGV.empty?

options[:verbose] = true if $VERBOSE 

puts options

if options[:verbose]
  @start = Time.now
end

ARGV.each do|a|
    puts a
end

if options[:verbose]
  elapsed = Time.now - @start
  puts 'Elapsed time: ' +  elapsed.to_s + ' seconds'
end
